// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AvailableProviders() {
  return window['go']['main']['App']['AvailableProviders']();
}

export function ConvertAudio(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ConvertAudio'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function InspectPath(arg1) {
  return window['go']['main']['App']['InspectPath'](arg1);
}

export function PreviewMetadata(arg1, arg2) {
  return window['go']['main']['App']['PreviewMetadata'](arg1, arg2);
}

export function ResolveMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveMetadata'](arg1, arg2, arg3, arg4);
}

export function SearchMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMetadata'](arg1, arg2, arg3);
}

export function SelectAudioDirectory() {
  return window['go']['main']['App']['SelectAudioDirectory']();
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectCoverFile() {
  return window['go']['main']['App']['SelectCoverFile']();
}

export function SelectMetadataFile() {
  return window['go']['main']['App']['SelectMetadataFile']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}
