// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AvailableProviders() {
  return window['go']['main']['App']['AvailableProviders']();
}

export function InspectPath(arg1) {
  return window['go']['main']['App']['InspectPath'](arg1);
}
