// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function AppVersion():Promise<string>;

export function AvailableProviders():Promise<Array<app.ProviderInfo>>;

export function InspectPath(arg1:string):Promise<main.InspectView>;
