// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AvailableProviders() {
  return window['go']['main']['App']['AvailableProviders']();
}

export function InspectPath(arg1) {
  return window['go']['main']['App']['InspectPath'](arg1);
}

export function SelectAudioDirectory() {
  return window['go']['main']['App']['SelectAudioDirectory']();
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectCoverFile() {
  return window['go']['main']['App']['SelectCoverFile']();
}

export function SelectMetadataFile() {
  return window['go']['main']['App']['SelectMetadataFile']();
}
